num1=int(input("enter 1st int :"))
num2=int(input("enter 2nd int :"))
num3=int(input("enter 3rd int :"))
num4=float(input("enter 1st float :"))
num5=float(input("enter 2nd float :"))
num6=float(input("enter 3rd float :"))
a=str(input("enter 1st string:"))
b=str(input("enter 2nd string:"))
c=complex(input("enter complex number:"))
print("1st int is:",num1)
print("2nd int is:",num2)
print("3rd int is:",num3)
print("1st float is:",num4)
print("2nd float is:",num5)
print("3rd float is:",num6)
print("1st string is:",a)
print("2nd string is:",b)
print("complex number is:",c)
