print("  ...       ... ")
print("  . ......... .  ")
print(" . =        =  . ")
print(" . 0        0  . ")
print(" .    o o      . ")
print("  .    =      .  ")
print("    .  .  .  .   ")
print("  .           .  ")
print(" .             . ")
print(".               .")
print(".               .")
print(" ............... ")
